### ISSUE TITLE
No attribute 'BME_I2C'

### ISSUE THREAD

**Issue by Thosch42** [teusH/MySense#1]
Hi!!
First of all - Very nice project!!
I tried to test a BME680 and run into the following problem:

```
4251 - Using BME680 config I2C 0 SDA on pin P8, SCL on pin P9
4254 - Traceback (most recent call last):
4258 -   File "meteo_test.py", line 30, in <module>
4263 - AttributeError: 'module' object has no attribute 'BME_I2C'
5506 - Pycom MicroPython 1.18.0 [v1.8.6-849-046b350] on 2018-06-01; LoPy4 with ESP32
```
I'm pretty new to MicroPython. As far as I understand, the BME680 library ist imported as BME. But the class in the BME library is called BME680. The BME_I2C class is defined in BME_I2C.py. But this library seems to be never imported.

Could you give me an advise?

Best regards,
Thomas

**Comment by teusH** [comment]
Issue has been resolved in a later release.
